# Generated by Django 5.2.7 on 2025-11-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asignatura', models.CharField(max_length=100, verbose_name='Asignatura')),
                ('tema', models.CharField(max_length=200, verbose_name='Tema a tratar')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y Hora')),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('online', 'Online')], default='presencial', max_length=20)),
                ('cupos', models.IntegerField(default=5, verbose_name='Cupos Disponibles')),
            ],
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
    ]
